server:
  port: 7776   #tomcat port
  compression:
    enabled: true

logging:
  level:
    root: INFO
    org.springframework.security: INFO
#    io.lettuce.core.protocol: TRACE
application:
  num-of-threads : 10
  wait-min-millis: 5
  wait-max-millis: 20
  log-period-millis: 60000
  is-fips: true
  sleep-after-error-period-millis: 1000
  max-retries-on-failure: 3
  retry-delay-millis: 500

spring:
  redis:
    client-type : lettuce
    host: 10.70.220.15
    port: 6379
    username:
    password:
    ssl: true
#    ssl: false
    ssl-verify : false
    maxRetriesOnFailure: 1
    connectTimeout : 30000
    lettuce:
      pool:
        enabled: true
        maxActive: 12
        minIdle: 12
      socketOptions.keepalive: true
    jedis:
      pool:
        enabled: true
        maxActive: 12
        minIdle: 12

# Prometheus metrics
management:
  server:
    port: 19019
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health, info, prometheus
  endpoint:
    health:
      enabled: true
      # /actuator/health/readiness
      # /actuator/health/liveness
      probes:
        enabled: true
    info:
      enabled: true
    prometheus:
      enabled: true
